# Development environment configuration
# Inherits from base.yaml and overrides specific settings for development

# Override training settings for faster development
training:
  epochs: 70
  batch_size: 1024  # Use larger batch size for faster training
  learning_rate: 0.0001
  
  # Enable early stopping with lower patience for faster iterations
  early_stopping:
    enabled: true
    patience: 5
    min_delta: 0.01

# Data configuration for development
data:
  num_workers: 4
  
  # Use smaller dataset for faster development
  data_fraction: 0.6
  
  # Enable data validation in development
  validation:
    integrity_checks: true
    max_value_threshold: 1e6
    variance_threshold: 0.0

# Experiment tracking for development
experiment:
  tracking:
    enabled: true
    project_name: "cbramod-dev"
    
  logging:
    level: "DEBUG"
    save_logs: true
    
  checkpointing:
    enabled: true
    save_best_only: false
    save_frequency: 2  # Save more frequently in development

# Paths for development
paths:
  # Use relative paths in development
  datasets_dir: "Datasets/Final_dataset"
  model_dir: "saved_models/dev"
  log_dir: "logs/dev"
  results_dir: "results/dev"
  temp_dir: "/tmp/cbramod/dev"
  cache_dir: "cache/dev"

# Device configuration for development
device:
  cuda:
    enabled: true
    device_id: 0
    
  # Disable distributed training in development
  distributed:
    enabled: false

# Enable debug mode
debug:
  enabled: true
  profiling: false
  memory_profiling: false