# Testing environment configuration
# Optimized for running tests and CI/CD pipelines

# Testing training settings (minimal for fast execution)
training:
  epochs: 5
  batch_size: 16
  learning_rate: 0.001
  
  early_stopping:
    enabled: false  # Disable early stopping in tests

# Data configuration for testing
data:
  num_workers: 2
  
  # Use very small dataset for testing
  data_fraction: 0.01
  
  validation:
    integrity_checks: true
    max_value_threshold: 1e6
    variance_threshold: 0.0

# Disable experiment tracking for testing
experiment:
  tracking:
    enabled: false
    
  logging:
    level: "WARNING"
    save_logs: false
    
  checkpointing:
    enabled: false

# Testing paths
paths:
  datasets_dir: "Datasets/Final_dataset"
  model_dir: "/tmp/test_models"
  log_dir: "/tmp/test_logs"
  results_dir: "/tmp/test_results"
  temp_dir: "/tmp/cbramod/test"
  cache_dir: "/tmp/test_cache"

# Device configuration for testing
device:
  cuda:
    enabled: false  # Use CPU for testing by default
    device_id: 0
    
  distributed:
    enabled: false

# Enable debug mode for testing
debug:
  enabled: true
  profiling: false
  memory_profiling: false

# Testing-specific settings
testing:
  deterministic: true
  fast_dev_run: true
  overfit_batches: 0.01